services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
  backend:
    build: ./server
    ports:
      - "4545:4545"
 
    depends_on:
      - mongo
      - postgres
    networks:
      - app-network
  frontend:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
