version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: mongodbNonosql
    ports:
      - "27017:27017"
    networks:
      - app-network
    # volumes:
    #   - ./initDemoDaten/nosql:/docker-entrypoint-initdb.d
    # command: bash /docker-entrypoint-initdb.d/import.sh

   
  postgres:
    image: postgres:latest
    container_name: postgresSQLdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: barber

    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      #   # - ./dbdataSQL:/var/lib/postgresql/data
      - ./initDemoDaten/sql:/docker-entrypoint-initdb.d
  backend:
    build: ./server
    ports:
      - "4545:4545"
    environment:
      - DB_URI_MONGODB=mongodb://mongo:27017/barber
      - DB_URI_POSTGRESQL=postgresql://postgres:postgres@postgres:5432/barber
    depends_on:
      - mongo
      - postgres
    networks:
      - app-network
  frontend:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
# volumes:
#   dbdataSQL:
#   dbdataMongodb:
